---
title: "hotspots"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# What are the best walleye recruit lakes
```{r}
efish_wae <- read.csv("./data/yoy_catch_data.csv")

total_ef_wae <- efish_wae %>%
  group_by(lake_id) %>%
  summarize(n = n(), mean_CPUE = mean(cpue), 
            sd.CPUE = sd(cpue), 
            lat = unique(y),
            long = unique(x)) %>% 
  distinct(lake_id, .keep_all = T) %>%
  ungroup() %>%
  slice_max(mean_CPUE, n = 19)
  
```


# What are the best adult walleye catch lakes
```{r}
adult_wae <- read.csv("./data/adult_catch_data.csv")


best_adult_walleye <- adult_wae %>%
  group_by(lake_id, lake_name.1) %>%
  summarize(n = n(), mean_CPUE = mean(cpue), 
            sd.CPUE = sd(cpue), 
            lat = unique(y),
            long = unique(x)) %>%
  #dplyr::filter(n > 2) %>%
  #filter(mean_CPUE > 0) %>%
  ungroup() %>% 
  slice_max(mean_CPUE, n = 71) %>%
  dplyr::select(!lake_name.1)


```

```{r}
mn_counties <- map_data("state", "Minnesota")

adult_wae %>% 
  group_by(lake_id) %>%
  summarise(mean_CPUE = mean(cpue),
            lat = unique(y),
            long = unique(x)) %>%
  mutate(sqrt_cpue = sqrt(mean_CPUE)) %>%
  ggplot() + 
  geom_polygon(data = mn_counties, aes(x = long, y = lat, group = group), 
               colour="black", fill="NA", lwd=1 )  + 
  # color changes state outline, fill changes state fill
  coord_fixed(1.3) +
  geom_point(aes(x = long, y = lat, size = mean_CPUE), pch = 21, alpha = 0.75, color = "black", fill = "grey") +
  theme(plot.title = element_text(hjust = 0.5, size = 18),
        plot.subtitle = element_text(hjust = 0.5),
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), legend.position = "none") + 
  labs(
       x = "Longitude", y = "Latitude")
ggsave("./figures/mean_abundance_gn.jpeg", width = 7, height = 7)
```


```{r}
best_adult_walleye_year <- adult_wae %>%
  mutate(hotspot = ifelse(cpue > 12.8, 1, 0)) %>%
  #mutate(hotspot = as.factor(hotspot)) %>%
  dplyr::select(lake_id, lake_name.1, x, y, cpue, count, year, julian_day, hotspot)

best_adult_walleye_year %>% ggplot() +
  geom_point(aes(x = year, y = log(cpue), color = hotspot))

temp <- best_adult_walleye_year %>% group_by(lake_id) %>% summarize(n = sum(hotspot)) %>%
  filter(n>0) %>%
  sample_frac(.025)

best_adult_walleye_year %>% filter(lake_id %in% temp$lake_id) %>%
  ggplot(aes(x = year, y = cpue, color = as.factor(lake_name.1))) +
  geom_point(aes(size = hotspot)) +
  geom_line() +
  geom_hline(yintercept = 12.8) +
  theme(legend.position = "none")
ggsave("./figures/brightspots.time.jpeg")

most_surveyed = slice_max(best_adult_walleye, n, n = 5)
adult_wae %>% dplyr::filter(lake_id %in% most_surveyed$lake_id) %>%
  mutate(hotspot = ifelse(cpue > 12.8, 1, 0)) %>%
  ggplot(aes(x = year, y = log(cpue), color = as.factor(lake_name.1))) +
  geom_point(aes(size = hotspot)) +
  geom_line() +
  geom_hline(yintercept = log(12.8)) 
ggsave("./figures/big_hotspots.time.jpeg")
```


# What are the best adult walleye size lakes
```{r}
size_wae <- read.csv("./data/adult_size_data.csv")


best_size_walleye <- size_wae %>%
  group_by(lake_id, lake_name.1) %>%
  summarize(n = n(), mean_size = mean(p_over500), 
            sd_size = sd(p_over500), 
            lat = unique(y),
            long = unique(x)) %>%
  #filter(mean_CPUE > 0) %>%
  ungroup() %>% 
  slice_max(mean_size, n = 47) %>%
  dplyr::select(!lake_name.1)
```


# Overlap between best recruits and catches?
```{r}
best_adult_walleye %>% dplyr::filter(lake_id %in% total_ef_wae$lake_id)
```

# Plot combined hotspots
```{r}
mn_counties <- map_data("state", "Minnesota")

total_ef_wae$method = "YOY"
best_adult_walleye$method = "Gill-net"
combined.hotspot <- rbind(total_ef_wae, best_adult_walleye) #%>%
  mutate(method = ifelse(lake_id %in% best_adult_walleye$lake_id & 
                           lake_id %in% total_ef_wae$lake_id,
                         "Both", method))

group.colors <- c(`YOY` = "black", `Gill-net` = "blue", `Both` = "red")





combined.hotspot %>%
  mutate(method = ifelse(lake_id %in% best_adult_walleye$lake_id & 
                           lake_id %in% total_ef_wae$lake_id,
                         "Both", method)) %>%
  ggplot() + 
  geom_polygon(data = mn_counties, aes(x = long, y = lat, group = group), 
               colour="black", fill="NA", lwd=1 )  + 
  # color changes state outline, fill changes state fill
  coord_fixed(1.3) +
  geom_point(aes(x = long, y = lat, color = method)) + 
  scale_color_manual(values = group.colors) +
  theme(plot.title = element_text(hjust = 0.5, size = 18),
        plot.subtitle = element_text(hjust = 0.5),
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  labs(title = "Hot Spots",
       subtitle = "Top 10% of lakes for each category",
       x = "Longitude", y = "Latitude", color = "Method") 

#ggsave("./figures/hotspots.jpeg")  
```


# Add in size hot spots
```{r}
size_hotspot <- best_size_walleye %>% 
  rename(mean_CPUE = mean_size, sd.CPUE = sd_size) %>%
  mutate(method = "Size")

combined.hotspots <- rbind(combined.hotspot, size_hotspot) 

#write.csv(combined.hotspots, "./data/hotspots.csv", row.names = F)
```

